name: Build RocksDB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux-x64:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config autoconf automake libtool curl unzip zip
      - name: Build Linux x86_64 package
        run: ./build.sh linuxX64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-linux-x86_64
          path: build/archives/rocksdb-linux-x86_64.zip

  linux-arm64:
    name: Linux ARM64
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config autoconf automake libtool curl unzip zip
      - name: Build Linux ARM64 package
        run: ./build.sh linuxArm64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-linux-arm64
          path: build/archives/rocksdb-linux-arm64.zip

  mingw-x64:
    name: Windows (MinGW) x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config autoconf automake libtool curl unzip zip mingw-w64
      - name: Build Windows MinGW package
        run: ./build.sh mingwX64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-mingw-x86_64
          path: build/archives/rocksdb-mingw-x86_64.zip

  macos-x64:
    name: macOS x86_64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build macOS x86_64 package
        run: ./build.sh macosX64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-macos-x86_64
          path: build/archives/rocksdb-macos-x86_64.zip

  macos-arm64:
    name: macOS ARM64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build macOS ARM64 package
        run: ./build.sh macosArm64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-macos-arm64
          path: build/archives/rocksdb-macos-arm64.zip

  ios-arm64:
    name: iOS ARM64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build iOS ARM64 package
        run: ./build.sh iosArm64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-ios-arm64
          path: build/archives/rocksdb-ios-arm64.zip

  ios-simulator-arm64:
    name: iOS Simulator ARM64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build iOS Simulator ARM64 package
        run: ./build.sh iosSimulatorArm64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-ios-simulator-arm64
          path: build/archives/rocksdb-ios-simulator-arm64.zip

  watchos-arm64:
    name: watchOS ARM64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build watchOS ARM64 package
        run: ./build.sh watchosArm64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-watchos-arm64
          path: build/archives/rocksdb-watchos-arm64.zip

  tvos-arm64:
    name: tvOS ARM64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build tvOS ARM64 package
        run: ./build.sh tvosArm64
      - uses: actions/upload-artifact@v4
        with:
          name: rocksdb-tvos-arm64
          path: build/archives/rocksdb-tvos-arm64.zip

  publish-release:
    name: Publish Release
    needs:
      - linux-x64
      - linux-arm64
      - mingw-x64
      - macos-x64
      - macos-arm64
      - ios-arm64
      - ios-simulator-arm64
      - watchos-arm64
      - tvos-arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: List downloaded artifacts
        run: ls -R artifacts
      - name: Set release tag
        id: release_tag
        run: echo "tag=$(date +'%Y%m%dT%H%M%S')Z" >> "$GITHUB_OUTPUT"
      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.zip
          name: RocksDB builds ${{ steps.release_tag.outputs.tag }}
          tag_name: ${{ steps.release_tag.outputs.tag }}
          draft: false
          prerelease: false
